AllCops:
  Exclude:
    - '**/Vagrantfile'
    - '**/Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**'
    - '**/Rakefile'
    - '**/Guardfile'
    - 'vendor/**/*'
  DisplayStyleGuide: true
